// MIT License

#ifndef WISP_APP_H
#define WISP_APP_H

#include <common/fs.h>

namespace Wisp
{
class CApplication
{
public:
    fs_path m_ExePath;
    fs_path m_UOPath;

protected:
    virtual void OnMainLoop() {}

public:
    CApplication();
    virtual ~CApplication();
    virtual void Init();
    int Run();
    // To use with any data generated by the client itself
    // eg. .xuo files, .cfg files.
    fs_path FilePath(const char *str, ...) const;
    // Only for ephemeral data that needs to be easily accessible to the user
    // eg. screenshots, log files, plugins?
    fs_path ExeFilePath(const char *str, ...) const;
    fs_path UOFilesPath(const char *str, ...) const;
    fs_path UOFilesPath(const astr_t &str, ...) const;
};

}; // namespace Wisp

#endif // WISP_APP_H
